// Portfolio data - all content in one place

export const personal = {
  name: 'Larry David',
  title: 'Full Stack Web Developer',
  subtitle: 'Building scalable web applications',
  email: 'larrydavid7730@gmail.com',
  phone: '+234 913 119 3359',
  location: 'Uyo, Nigeria',
  github: 'https://github.com/L1a6',
  linkedin: 'https://linkedin.com/in/larrydavid',
  twitter: 'https://x.com/larrydaves2',
  instagram: 'https://www.instagram.com/larrydaves1',
  whatsapp: 'https://wa.me/2349131193359',
  avatar: '/hero.png',
  aboutImage: '/about-image.jpg',
  cv: '/cv.pdf',
  status: 'Probably coding',
  bio: `I specialize in transforming complex challenges into elegant, high-performance solutions. With a focus on modern web technologies and clean architecture, I build applications that users love — from healthcare platforms to e-commerce systems.`,
  description: `I build web applications engineered for healthcare platforms, e-commerce systems, digital education solutions, and growing businesses that require scalable infrastructure and performance.`,
};

export const projects = [
  {
    id: 'vitalcare',
    title: 'VitalCare',
    description: 'Comprehensive healthcare management platform featuring appointment scheduling, medical records management, and secure patient-provider communication with HIPAA-compliant data handling.',
    excerpt: 'Healthcare management platform with HIPAA compliance',
    category: 'Healthcare',
    image: '/1768857928205.jpg',
    url: 'https://vitalcare.com',
    github: 'https://github.com/L1a6/vitalcare',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'PostgreSQL'],
    featured: true,
  },
  {
    id: 'adeips',
    title: 'Adeips Official Website',
    description: 'Professional website for a public speaking school with custom admin dashboard, role-based authentication, course management system, and student enrollment portal with payment integration.',
    excerpt: 'Public speaking school with admin dashboard',
    category: 'Education',
    image: '/1768883403276~2.jpg',
    url: 'https://adeips-official-website.vercel.app',
    github: 'https://github.com/L1a6/adeips-official-website',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS'],
    featured: true,
  },
  {
    id: 'framez',
    title: 'Framez',
    description: 'Social media mobile application with photo sharing capabilities, real-time notifications, user engagement features, and optimized media delivery using cloud storage and CDN integration.',
    excerpt: 'Social media app with real-time features',
    category: 'Mobile',
    image: '/1768096100770~2.jpg',
    url: 'https://framez.app',
    github: 'https://github.com/L1a6/framez-social-app',
    technologies: ['React Native', 'Expo', 'NativeWind', 'Supabase'],
    featured: false,
  },
  {
    id: 'novatickets',
    title: 'NovaTickets',
    description: 'Ticket management system with JWT authentication, real-time dashboard analytics, full CRUD operations, team collaboration features, and role-based access control for enterprise workflows.',
    excerpt: 'Enterprise ticket management with analytics',
    category: 'SaaS',
    image: '/blog1.jpg',
    url: 'https://nova-tickets.vercel.app',
    github: 'https://github.com/L1a6/nova-tickets',
    technologies: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS', 'JWT'],
    featured: false,
  },
  {
    id: 'audiophile',
    title: 'E-commerce Audiophile',
    description: 'High-performance e-commerce platform for premium audio equipment featuring Stripe payment processing, product catalog with advanced filtering, shopping cart functionality, and responsive checkout flow.',
    excerpt: 'Premium audio e-commerce with Stripe payments',
    category: 'E-commerce',
    image: '/blog2.jpg',
    url: 'https://audiophile-ecommerce-com.vercel.app',
    github: 'https://github.com/L1a6/audiophile-ecommerce.com',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe', 'Convex'],
    featured: false,
  },
];

export const testimonials = [
  {
    quote: "Working with him transformed how I approach product development.",
    author: "Goodness Mbakara",
    authorLink: "https://goodnessmbakara.vercel.app/",
    role: "Founder",
    company: "Voxcard",
    companyLink: "https://voxcard.vercel.app/",
    image: "/testimonials1.jpg",
  },
  {
    quote: "His code architecture is the most elegant I've ever worked with.",
    author: "Uwakmfon",
    authorLink: "https://www.linkedin.com/in/uwakmfon1",
    role: "Backend Developer",
    company: "Softsuites",
    companyLink: "https://softsuite.ng/",
    image: "/testimonials2.jpeg",
  },
  {
    quote: "Pure craftsmanship in every single detail he delivers.",
    author: "Micah",
    authorLink: "https://micahthegreat.netlify.app",
    role: "Full Stack Developer",
    company: "Sparopay",
    companyLink: "#",
    image: "/testimonials3.jpeg",
  },
];

export const skills = {
  frontend: ['React', 'Next.js', 'TypeScript', 'Svelte', 'Tailwind CSS', 'GSAP'],
  backend: ['Node.js', 'Express', 'PostgreSQL', 'Supabase', 'Convex'],
  mobile: ['React Native', 'Expo'],
  tools: ['Git', 'Figma', 'Docker', 'Vercel', 'Postman'],
};

export const techStack = [
  { name: 'Next.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg', invertDark: true },
  { name: 'TypeScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
  { name: 'React', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  { name: 'Node.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
  { name: 'Tailwind CSS', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
  { name: 'Supabase', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg' },
  { name: 'JavaScript', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
  { name: 'Git', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
  { name: 'PostgreSQL', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
  { name: 'Docker', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  { name: 'Vercel', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg', invertDark: true },
  { name: 'Express.js', src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg', invertDark: true },
];

export const approach = [
  {
    number: '01',
    title: 'Plan',
    description: 'Strategic planning and research to define goals, understand your audience, and establish technical requirements.',
    details: ['Requirements analysis', 'User research', 'Technical architecture'],
    animation: '/animations/plan.lottie',
    color: 'from-blue-500/10 to-indigo-500/5',
  },
  {
    number: '02',
    title: 'Build',
    description: 'Development using modern frameworks and best practices to create scalable, high-performance applications.',
    details: ['Modern tech implementation', 'Component architecture', 'API integration'],
    animation: '/animations/build.lottie',
    color: 'from-emerald-500/10 to-teal-500/5',
  },
  {
    number: '03',
    title: 'Test',
    description: 'Comprehensive testing across devices and browsers to ensure quality and reliability.',
    details: ['Cross-browser testing', 'Performance audits', 'User acceptance'],
    animation: '/animations/test.lottie',
    color: 'from-amber-500/10 to-orange-500/5',
  },
  {
    number: '04',
    title: 'Deploy',
    description: 'Production launch with monitoring and ongoing support for long-term success.',
    details: ['Production setup', 'CI/CD pipeline', 'Monitoring & support'],
    animation: '/animations/deploy.lottie',
    color: 'from-purple-500/10 to-pink-500/5',
  },
];
